### PR TITLE
fix(phone/notification-bar): center time text

### LINKED ISSUE #511: Bug(Phone Header): time isn't centered with the frame.
### Developement Issue

No

### Phone Version

Every single god damn one

### Issue Description

I would rather not but if you inist... [>!](https://i.imgur.com/8t70Rk1.png)

### Issue Reproduction

.

### Evidence

_No response_

### PR DESCRIPTION
**Pull request by LukeWasTakenn**
Resolves #511, the biggest priority issue of them all

### CODE REVIEW

**Comment by TasoOneAsia** [comment]
!! URGENT REVIEW REQUIRED !!

File: phone/src/os/notifications/components/NotificationBar.tsx [hunk 1]
```diff
@@ -76,6 +76,7 @@ export const NotificationBar = () => {
         className={classes.root}
         container
         justifyContent="space-between"
+        alignItems="center"
```
Comment (itschip) [inline phone/src/os/notifications/components/NotificationBar.tsx:79]: 🤔 🍔 💭 🤔

**Comment by RockySouthpaw** [comment]
Where is the reviews! 😡😡😡😡😡😡 IMPORTANT ISSUE RESOLUTION!

**Comment by itschip** [comment]
> Where is the reviews! 😡😡😡😡😡😡 IMPORTANT ISSUE RESOLUTION!

I took the day off. Reviewing this will require a lot of focus.

**Comment by RockySouthpaw** [comment]
> > Where is the reviews! 😡😡😡😡😡😡 IMPORTANT ISSUE RESOLUTION!
> 
> I took the day off. Reviewing this will require a lot of focus.

Good you need to be well rested to tackle this

**Comment by AvarianKnight** [comment]
Look at all those failed tests 😨

File: phone/src/os/notifications/components/NotificationBar.tsx (hunk 1 above)
Comment (itschip) [inline phone/src/os/notifications/components/NotificationBar.tsx:79]: This will only center the 'time' horizontally. I thought the issue here was that the vertical alignment between the camera on the frame and the 'time' was not in center? @RockySouthpaw Please confirm.

**Comment by itschip** [comment]
@LukeWasTakenn Take a look at styling. The reason of the alignment, is that `classes.root` has a `paddingLeft` property that has a higher px value, than the `paddingRight`. Make them the same, and you should be good.

**Review by itschip — APPROVED** [review]

**Comment by LukeWasTakenn** [comment]
> @LukeWasTakenn Take a look at styling. The reason of the alignment, is that `classes.root` has a `paddingLeft` property that has a higher px value, than the `paddingRight`. Make them the same, and you should be good.

I honestly didn't even notice the wrong horizontal alignment lol,

Should be good now boss

**Review by dunak-debug — COMMENTED** [review]
🆗 🆗

**Comment by RockySouthpaw** [comment]
> @LukeWasTakenn Take a look at styling. The reason of the alignment, is that `classes.root` has a `paddingLeft` property that has a higher px value, than the `paddingRight`. Make them the same, and you should be good.

Like I said, once you see it you can’t unsee it
