### PR TITLE
Disable walking when an inputfield is focused

### LINKED ISSUE #227: Bug: While using text fields, controls are enabled so movement occurs/menus open.
**Describe the bug**
- If a server has any menu bound to any key that is typically used when writing a message (A-Z, commas, periods, ect) then that menu will pop up. 
- People will move slightly every time they type the letters `W,A,S,D` as we do not freeze them now. 

The only solution I have would be to disable all control actions if they're clicking on a text field or `SetNuiFocusKeepInput(false)` within text boxes. 

Issue was introduced in the following PR: https://github.com/project-error/new-phone-who-dis/pull/212

### PR DESCRIPTION
**Pull request by NuttyShrimp**
resolves #227

### CODE REVIEW

**Review by jfrader — APPROVED** [review]
Code looks good to me.

Just a thought, can you rename "bool" to something more meaningful?

Thanks for your contribution!

File: phone/src/ui/components/Input.tsx [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+
+const ToggleKeys = ()=>{
+	const Nui = useNuiRequest();
+	const toggle = React.useCallback((keepGameFocus:boolean)=>{
+		Nui.send(PhoneEvents.TOGGLE_KEYS, {
+			keepGameFocus,
+		});
+	}, [Nui])
+	return React.useMemo(()=>({toggle}), [toggle])
+}
```
Comment (jfrader) [inline phone/src/ui/components/Input.tsx:15]:
```suggestion
const useToggleFocus = () =>{
	const Nui = useNuiRequest();
	return  React.useCallback((keepGameFocus: boolean)=>{
		Nui.send(PhoneEvents.TOGGLE_KEYS, {
			keepGameFocus,
		});
	}, [Nui]);
}
```

File: phone/src/ui/components/Input.tsx [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+
+export const TextField = (props) => {
+	const KeysHandler = ToggleKeys()
```
Comment (jfrader) [inline phone/src/ui/components/Input.tsx:18]:
```suggestion
	const toggleFocus = useToggleFocus();
```

File: phone/src/ui/components/Input.tsx [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+				if (props.onBlur) {
+					props.onBlur(e);
+				}
+			}}
+		/>
+	);
+};
+
+export const InputBase = (props) => {
+	const KeysHandler = ToggleKeys()
```
Comment (jfrader) [inline phone/src/ui/components/Input.tsx:39]:
```suggestion
	const toggleFocus = useToggleFocus();
```

File: phone/src/ui/components/Input.tsx [hunk 4]
```diff
@@ -0,0 +1,57 @@
...
+	return React.useMemo(()=>({toggle}), [toggle])
+}
+
+export const TextField = (props) => {
+	const KeysHandler = ToggleKeys()
+  return(
+		<MUITextField
+			{...props}
+			onFocus={(e)=>{
+				KeysHandler.toggle(false)
```
Comment (jfrader) [inline phone/src/ui/components/Input.tsx:23]:
```suggestion
				toggleFocus(false);
```

File: phone/src/ui/components/Input.tsx [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+				if (props.onFocus) {
+					props.onFocus(e);
+				}
+			}}
+			onBlur={(e)=>{
+				KeysHandler.toggle(true)
```
Comment (jfrader) [inline phone/src/ui/components/Input.tsx:29]: toggleFocus(true);

**Review by jfrader — CHANGES_REQUESTED** [review]
Just found some possible improvements, do you mind adjusting that?

**Comment by RockySouthpaw** [comment]
I’ll test this in roughly 12 hours.

**Comment by NuttyShrimp** [comment]
> Just found some possible improvements, do you mind adjusting that?

I'll push them during the day, thanks for the feedback!

**Review by jfrader — APPROVED** [review]

**Review by RockySouthpaw — APPROVED** [review]
Tested and works well. 

Thank you for the PR :). Will let taso or chip review it too before merging.

File: resources/client/cl_main.ts [hunk 6]
```diff
@@ -179,6 +179,14 @@ on(`__cfx_nui:${PhoneEvents.CLOSE_PHONE}`, async (data: any, cb: Function) => {
   cb();
 }); // Called for when the phone is closed via the UI.
 
+RegisterNuiCallbackType(PhoneEvents.TOGGLE_KEYS);
+on(`__cfx_nui:${PhoneEvents.TOGGLE_KEYS}`, async (data: any, cb: Function) => {
+  if (isPhoneOpen) {
+		SetNuiFocusKeepInput(data.keepGameFocus);
```
Comment (TasoOneAsia) [inline resources/client/cl_main.ts:185]: Indentation here is a little odd.

File: phone/src/ui/components/Input.tsx [hunk 7]
```diff
@@ -0,0 +1,59 @@
+import React from 'react';
+import MUITextField from '@material-ui/core/TextField';
+import MUIInputBase from '@material-ui/core/InputBase';
+import { useNuiRequest } from 'fivem-nui-react-lib';
+import { PhoneEvents } from '../../../../typings/phone';
+
+const useToggleFocus = () => {
+  const Nui = useNuiRequest();
+  return React.useCallback(
```
Comment (TasoOneAsia) [inline phone/src/ui/components/Input.tsx:9]: For code styling, we use the de-structured imports. i.e
```ts
{ useCallback } 
```

**Review by TasoOneAsia — CHANGES_REQUESTED** [review]
Looks good aside from a couple things.

File: resources/client/cl_main.ts (hunk 6 above)
Comment (NuttyShrimp) [reply resources/client/cl_main.ts:185]: Seems to be a github issue because the indentation is good in my editor. Is probably because I use tabs instead of spaces but will change it to spaces hopefully that will fix the oddness
image

**Comment by RockySouthpaw** [comment]
Changes were applied so going to merge this
